// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ynfmrcmuecbxpgadnvzn.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InluZm1yY211ZWNieHBnYWRudnpuIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTM5NzQ0MzUsImV4cCI6MjA2OTU1MDQzNX0.riDYNK1UKG7LnYOiqqTq-zPKTi1BlTfYqyW0a7lqwJs";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});